/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/clients/': RouteRecordInfo<'/admin/clients/', '/admin/clients', Record<never, never>, Record<never, never>>,
    '/admin/employees/': RouteRecordInfo<'/admin/employees/', '/admin/employees', Record<never, never>, Record<never, never>>,
    '/admin/stats': RouteRecordInfo<'/admin/stats', '/admin/stats', Record<never, never>, Record<never, never>>,
    '/admin/tests/': RouteRecordInfo<'/admin/tests/', '/admin/tests', Record<never, never>, Record<never, never>>,
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/chat/client': RouteRecordInfo<'/chat/client', '/chat/client', Record<never, never>, Record<never, never>>,
    '/chat/operator': RouteRecordInfo<'/chat/operator', '/chat/operator', Record<never, never>, Record<never, never>>,
    '/client/profile': RouteRecordInfo<'/client/profile', '/client/profile', Record<never, never>, Record<never, never>>,
    '/communications/': RouteRecordInfo<'/communications/', '/communications', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/employee/profile': RouteRecordInfo<'/employee/profile', '/employee/profile', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/tests/': RouteRecordInfo<'/tests/', '/tests', Record<never, never>, Record<never, never>>,
    '/tests/results/[id]': RouteRecordInfo<'/tests/results/[id]', '/tests/results/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tests/take/[id]': RouteRecordInfo<'/tests/take/[id]', '/tests/take/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
